num1 = eval(input("Escribe un número: "))
num2 = eval(input("Escribe otro número: "))

print("Menu")
print("1. Suma")
print("2. Resta")
print("3. Multiplicación")
print("4. División")
print("")
opcion = eval(input("Opción: "))